
<footer>
<div class="wrapper">

	<p>Lutecia No. 42, Colonia Lomas Estrella, 2da. Sección,<br/>
	Iztapalapa, México D.F.,<br/>
	Tel. (55) 12-09-17-75<br/>
	<a href="mailto:ventas@casasmaxhome.com" target="_self">ventas@casasmaxhome.com</a></p>
	
	<p class="mt20"><strong>Un proyecto de</strong></p>
	<a href="http://gwep.com.mx" target="_blank"><img src="images/GWEP_logo-2.png" alt="GWEP GROUP" /></a>
	
<div class="clearfix"></div>
</div>
</footer>