
<header>
<div class="wrapper">

<a href="index.php" target="_self" id="logo">Lutecia</a>

<div id="slogan" class="w300 floatl mt20 ml20">
	<h2>Un lugar privilegiado</h2>
	<img src="images/pleca.png"/>
</div>

<div class="clearfix"></div>

<ul id="menu">
	<li><a href="casas.php" target="_self">Las Casas</a>
		<ul class="dropdown dpwnCas">
			<li><a href="corona.php" target="_self">Modelo Corona</a></li>
			<li><a href="herradura.php" target="_self">Modelo Herradura</a></li>
			<li><a href="espuela.php" target="_self">Modelo Espuela</a></li>
		</ul>	
	</li>
	<li><a href="amenidades.php" target="_self">Amenidades</a></li>
	<li><a href="video.php" target="_self">Video</a></li>
	<li><a href="historias.php" target="_self">Historias</a></li>
	<li><a href="ubicacion.php" target="_self">Ubicación</a></li>
	<li><a href="contacto.php" target="_self">Contacto</a>
		<ul class="dropdown dpwnCon">
			<li><a href="contacto.php" target="_self">Mándanos un e-mail</a></li>
			<li><a href="contacto2.php" target="_self">Agenda una cita</a></li>
			<li><a href="contacto3.php" target="_self">Te llamamos</a></li>
		</ul>
	</li>
	<div class="clearfix"></div>
</ul>

<div class="clearfix"></div>

</div>
</header>

<div id="call-to-call">
	<p>Agenda una cita: (55) 12-09-17-75</p>
</div>

<a href="#" id="top">TOP</a>





