	
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimal-ui">
	
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />	
	<meta charset="utf-8" />
	
	<meta name="author" content="Sandra Bermudez @ bulabe.com" />
	<meta name="keywords" content="casas, créditos casas, inmuebles, inmobiliaria México, arquitectura, comprar casa, departamentos"/>
	
	<meta property="og:title" content="Real de Lutecia" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="Venta de Casas Nuevas en Lomas Estrella, Iztapalapa muy Cerca de Coyoacán. Casas Residenciales desde 108 m2 en Conjunto Residencial de Lujo. Haz una cita." />
	<meta property="og:url" content="http://realdelutecia.com" />
	<meta property="og:image" content="http://realdelutecia.com/images/lutecia-og.jpg" />
	
	<link href="http://fonts.googleapis.com/css?family=Istok+Web:400,700|Dancing+Script:700" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" type="text/css" href="style.css" />
	
	<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>
	<script type="text/javascript" src="js/fancydropdown.js"></script>
	<script type="text/javascript" src="js/jquery.lutecia.js"></script>
	
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51782211-4', 'auto');
  ga('send', 'pageview');
	</script>
